name: babel_binance
description: A comprehensive Dart wrapper for the Binance API, covering all major endpoints including Spot, Futures, Margin, and more.
version: 0.6.1
homepage: https://github.com/mayankjanmejay/babel_binance
# author: M1 Leopard < MayCloud.uk
repository: https://github.com/mayankjanmejay/babel_binance
topics:
  - api
  - binance
  - dart
  - cryptocurrency
  - trading
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.1
  crypto: ^3.0.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  test: ^1.25.2