/// Represents a trading signal generated by an algorithm
class TradeSignal {
  final String side; // 'BUY' or 'SELL'
  final String type; // 'MARKET', 'LIMIT', etc.
  final double quantity;
  final double? price; // For limit orders
  final String? timeInForce; // 'GTC', 'IOC', etc.
  final String reason; // Why this signal was generated
  final String algorithmName;
  final double confidence; // 0.0 to 1.0

  TradeSignal({
    required this.side,
    required this.type,
    required this.quantity,
    this.price,
    this.timeInForce,
    required this.reason,
    required this.algorithmName,
    this.confidence = 0.5,
  });

  @override
  String toString() {
    return 'TradeSignal($side $quantity @ ${price ?? "MARKET"} - $reason)';
  }
}
